import React from 'react';
import { useTheme } from '../../contexts/ThemeContext';

interface Props {
  onNavigate: (section: string) => void;
}

const UsageLimits: React.FC<Props> = ({ onNavigate }) => {
  const { themeColors } = useTheme();

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold" style={{ color: themeColors.text }}>AI Usage Limits</h1>
      <p style={{ color: themeColors.textSecondary }}>How AI usage quotas work in CodePark, including request limits, model access, and what happens when limits are reached.</p>
      <p style={{ color: themeColors.textSecondary }}>AI limits are designed to keep the platform fair, predictable, and sustainable while still being useful for real development work.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Overview</h2>
      <p style={{ color: themeColors.textSecondary }}>AI usage in CodePark is measured in requests.</p>
      <p style={{ color: themeColors.textSecondary }}>A request typically corresponds to:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>one prompt sent to the AI</li>
        <li>one response generated by the system</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>Limits apply per user, per day.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>What Counts as an AI Request</h2>
      <p style={{ color: themeColors.textSecondary }}>An AI request is counted when you:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>ask the AI to generate code</li>
        <li>request debugging help</li>
        <li>ask for refactoring suggestions</li>
        <li>request explanations or analysis</li>
        <li>use AI-powered editor actions</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>Each intentional interaction counts as one request, regardless of response length.</p>
      <p style={{ color: themeColors.textSecondary }}>Autocomplete-style suggestions may be handled separately depending on configuration.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Free Tier</h2>

      <h3 className="text-lg font-medium" style={{ color: themeColors.text }}>Included AI Usage</h3>
      <p style={{ color: themeColors.textSecondary }}>Free-tier users receive:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>50 AI requests per day</li>
        <li>Access to standard AI models</li>
        <li>Normal response speed</li>
        <li>Basic project context awareness</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>This tier is designed for:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>learning</li>
        <li>experimentation</li>
        <li>interviews</li>
        <li>casual or light usage</li>
      </ul>

      <h3 className="text-lg font-medium" style={{ color: themeColors.text }}>Free Tier Model Access</h3>
      <p style={{ color: themeColors.textSecondary }}>Free-tier requests typically use:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>reliable general-purpose models</li>
        <li>cost-efficient configurations</li>
        <li>limited reasoning depth</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>Model selection is handled automatically.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Pro Tier</h2>

      <h3 className="text-lg font-medium" style={{ color: themeColors.text }}>Included AI Usage</h3>
      <p style={{ color: themeColors.textSecondary }}>Pro-tier users receive:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>250 AI requests per day</li>
        <li>Access to advanced, high-performance models</li>
        <li>Faster response times</li>
        <li>Deeper project and multi-file context</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>This tier is designed for:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>daily development work</li>
        <li>debugging complex issues</li>
        <li>refactoring larger codebases</li>
        <li>sustained productivity</li>
      </ul>

      <h3 className="text-lg font-medium" style={{ color: themeColors.text }}>Pro Tier Model Access</h3>
      <p style={{ color: themeColors.textSecondary }}>Pro-tier requests may use:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>top-tier reasoning models</li>
        <li>higher-context models</li>
        <li>faster or priority inference</li>
        <li>deeper multi-file understanding</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>Exact models are selected dynamically for best results.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Daily Reset Behavior</h2>
      <p style={{ color: themeColors.textSecondary }}>AI usage limits reset once every 24 hours.</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>The reset is automatic</li>
        <li>No manual action is required</li>
        <li>Remaining requests do not roll over</li>
        <li>Reset timing is based on your account's local timezone</li>
      </ul>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>What Happens When You Hit the Limit</h2>
      <p style={{ color: themeColors.textSecondary }}>When you exhaust your daily AI quota:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>AI requests are temporarily disabled</li>
        <li>A clear message is shown in the editor</li>
        <li>Existing projects remain fully usable</li>
        <li>You can continue coding, running, and debugging manually</li>
        <li>AI access resumes automatically after the next reset</li>
      </ul>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Fair Use & Abuse Prevention</h2>
      <p style={{ color: themeColors.textSecondary }}>To ensure fair usage:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>excessive automated requests may be throttled</li>
        <li>scripted or abusive usage may be restricted</li>
        <li>attempts to bypass limits are blocked</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>These safeguards protect platform stability for everyone.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>AI Limits vs Collaboration</h2>
      <p style={{ color: themeColors.textSecondary }}>AI usage limits are:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>per user, not per project</li>
        <li>independent of collaborators</li>
        <li>unaffected by session size</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>Each user consumes their own quota.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Upgrading Between Tiers</h2>
      <p style={{ color: themeColors.textSecondary }}>You can upgrade to Pro at any time.</p>
      <p style={{ color: themeColors.textSecondary }}>When upgrading:</p>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>new limits apply immediately</li>
        <li>higher request quota becomes available</li>
        <li>advanced models are unlocked</li>
        <li>no project changes are required</li>
      </ul>
      <p style={{ color: themeColors.textSecondary }}>Downgrading takes effect at the next billing cycle.</p>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Best Practices</h2>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>Use AI for focused questions</li>
        <li>Avoid repeating similar prompts</li>
        <li>Combine AI with debugging tools</li>
        <li>Save AI usage for complex problems</li>
        <li>Review suggestions before applying</li>
        <li>Efficient prompts go a long way</li>
      </ul>

      <h2 className="text-xl font-semibold" style={{ color: themeColors.text }}>Summary</h2>
      <ul className="list-disc list-inside space-y-2 text-sm" style={{ color: themeColors.textSecondary }}>
        <li>AI usage is measured per request</li>
        <li>Free tier includes 50 requests/day</li>
        <li>Pro tier includes 250 requests/day</li>
        <li>Limits reset every 24 hours</li>
        <li>Model quality and speed vary by tier</li>
        <li>Coding continues even after limits are reached</li>
        <li>AI limits are meant to be transparent, fair, and predictable</li>
      </ul>

      <div className="pt-6 border-t border-gray-200 dark:border-gray-700">
        <h3 className="text-lg font-semibold mb-4" style={{ color: themeColors.text }}>Next Steps</h3>
        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => onNavigate('ai-prompting')}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm font-medium"
          >
            AI Prompting Guide →
          </button>
          <button
            onClick={() => onNavigate('ai-models')}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm font-medium"
          >
            AI Models & Selection →
          </button>
          <button
            onClick={() => onNavigate('ai-safety')}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm font-medium"
          >
            AI Safety & Guardrails →
          </button>
          <button
            onClick={() => onNavigate('free-vs-pro')}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm font-medium"
          >
            Free vs Pro vs Education Plan Comparison →
          </button>
        </div>
      </div>
    </div>
  );
};

export default UsageLimits;
