// ─── TOC Generator ───────────────────────────────────────────────────────────

import type { TOCItem } from './types';

/**
 * Slugifies a heading string to match the anchor IDs generated by
 * react-markdown (lowercase, spaces→hyphens, strip non-alphanum).
 */
export function slugifyHeading(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

/**
 * Extracts H2 and H3 headings from raw markdown content.
 * Skips headings inside fenced code blocks.
 */
export function extractTOC(markdown: string): TOCItem[] {
  const items: TOCItem[] = [];
  const lines = markdown.split('\n');
  let inCodeBlock = false;

  for (const line of lines) {
    if (line.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      continue;
    }
    if (inCodeBlock) continue;

    const h2 = line.match(/^##\s+(.+)/);
    const h3 = line.match(/^###\s+(.+)/);

    if (h2 && !line.startsWith('###')) {
      const text = h2[1].trim();
      items.push({ id: slugifyHeading(text), text, level: 2 });
    } else if (h3) {
      const text = h3[1].trim();
      items.push({ id: slugifyHeading(text), text, level: 3 });
    }
  }

  return items;
}
